---
dataset_config:
  dataset_name: mnist
  batch_size: 64
  root: data
  scale_type: -1-1
  train: True
  shuffle: True
  num_workers: 1

wandb_config:
  run: run_1
  project: diffugan
  tags:
    - GAN
    - deep_learning
  notes: This is a sample experiment
  group: gan

generator_config:
  latent_dimension: 100
  image_shape:
    - 1
    - 28
    - 28
  layer_sizes:
    - 128
    - 256
    - 512
  activation:
    name: ReLU
    params: {}
  final_activation: Tanh

discriminator_config:
  image_shape:
    - 1
    - 28
    - 28
  layer_sizes:
    - 512
    - 256
    - 128
  activation:
    name: LeakyReLU
    params:
      negative_slope: 0.2
  dropout_rate: 0.3

gan_config:
  generator_optimizer:
    name: Adam
    params:
      lr: 0.0001
      betas:
        - 0.5
        - 0.999
  discriminator_optimizer:
    name: Adam
    params:
      lr: 0.001
      betas:
        - 0.5
        - 0.999
  k: 1
  epochs: 20
  max_iteration_per_epoch:
  log_interval: 100
  image_plot_interval: 100
  wandb:
  generator_loss_to_use: "bce"
  max_step_for_og_loss: 100
  image_save_path:
  image_save_interval: 1000
